### ISSUE TITLE
Question: do you mind if we add support to ignore filename extensions in the generated type names?

### ISSUE THREAD

**Issue by ZachBray** [horiuchi/dtsgenerator#216]
#### Question: do you mind if we add support to ignore filename extensions in the generated type names?

We'd like to ignore filename extensions in the generated type names, as the extensions we use for our schema files add noise to the generated types.

Would you be happy with this change if I raised a PR? If so, what strategy would you like me to take? As the references are meant to be URIs (or part thereof) I take it this change may not make sense for all use-cases.

1. Change existing behaviour (which could break existing code) - major change
2. Introduce a new strategy for naming based on a command line option (defaulting to existing behaviour) - minor change

#### Related tests

https://github.com/horiuchi/dtsgenerator/blob/master/test/schemaid_test.ts#L26

For exampe: `http://x.y.z/rootschema.json` => `XYZ.RootschemaJson`

```typescript
test(new SchemaId('http://x.y.z/rootschema.json#', []), 'http://x.y.z/rootschema.json#', true, 'http://x.y.z/rootschema.json#', false, [], ['XYZ', 'RootschemaJson']);
```

#### Background

We're using JSON Schema to describe payloads (e.g., request/response/stream bodies) across our messaging oriented middleware. We make use of some tools, like jsonschema2pojo, to generate DTOs in Java. We hope to use this library to do the same for TypeScript.

Our existing DTOs sometimes contain relative references to other schemas, e.g., `RatesRequest.dto.yaml` may contain a reference `"$ref": "CurrencyPair.dto.yaml"`. We also generate service clients etc. from other yaml files. We use the extension of the file to differentiate the different declarations, e.g., services are described in `*.service.yaml` files.

**Comment by ZachBray** [comment]
Please see PR #217 for a possible solution along the lines of option (2) above.

**Comment by horiuchi** [comment]
Thank you for you pull request. But I would not merge that PR.

I think it should not be ignore file extensions for generated type name.
Because the type names generated from different urls should be different.
Then file extension would be included to generated type name.

I don't understand why you would be the same type names between Java and TypeScript?
When generated type names are different, what is there a problem?
My understanding, a JSON Schema is exists, you generate DTO of Java by `jsonschema2pojo`, and you generate DTO of TypeScript by `dtsgenerator`, but Those DTO type names are different.
But each type names are used by only each languages.

If you really want to change the generated type name, I think it is better to rewrite d.ts file by a script, like as `s/DtoYaml//g`.

**Comment by ZachBray** [comment]
> I don't understand why you would be the same type names between Java and TypeScript

That is not the point at all. I don't care if the names are different or in different namespaces.

To re-iterate:

> the extensions we use for our schema files add noise to the generated types

I care that the file-extension is included in the generated types.

> Because the type names generated from different urls should be different

Fair enough! Uniqueness is not guaranteed with these changes.

**Comment by ZachBray** [comment]
> Uniqueness is not guaranteed with these changes.

BTW your existing concatenation in the naming already means that there is not a unique mapping from URIs to type names.

**Comment by horiuchi** [comment]
> > Uniqueness is not guaranteed with these changes.

> BTW your existing concatenation in the naming already means that there is not a unique mapping from URIs to type names.

Sure, there are some restrictions by character set that can be used in URL and type name.
