### ISSUE TITLE
deeply nested allOf produces any type

### ISSUE THREAD

**Issue by ankrut** [horiuchi/dtsgenerator#443]
Hi, 
I stumbled about a strange behavior when using allOf. Looks like a bug. I could isolate the problem to the following minimal working example.

```yaml
openapi: 3.0.0

components:
  schemas:
    Bar:
      type: object
      description: OK
      properties:
        bar:
          type: string

    Foo:
      type: object
      description: OK
      properties:
        foo:
          allOf:
            - $ref: "#/components/schemas/Bar"

    FooBar:
      description: Not OK. 'foo' is of type any. Expected FooBar to have same structure as Foo
      allOf:
        - $ref: '#/components/schemas/Foo'

```

Using dtsgenerator v3.3.0 creates the following result.

```ts
declare namespace Components {
    namespace Schemas {
        /**
         * OK
         */
        export interface Bar {
            bar?: string;
        }
        /**
         * OK
         */
        export interface Foo {
            /**
             * OK
             */
            foo?: {
                bar?: string;
            };
        }
        /**
         * Not OK. 'foo' is of type any. Expected FooBar to have same structure as Foo
         */
        export interface FooBar {
            foo?: any;
        }
    }
}
```

**Comment by 0gust1** [comment]
I think I also noticed this behavior when working on my API definition, and it seems it's gone since I started using a dereferenced json API definition file as input of dtsgenerator.

Do you still have the problem if you use a bundler (like `swagger-cli`) to generate a dereferenced file to give to dtsgenerator?
Something like `swagger-cli bundle --dereference -t json -o openapi_deref.json src/index.yaml && dtsgen --out index.d.ts openapi_deref.json`

**Comment by 0gust1** [comment]
Before that, check also if your problem isn't resolved by the last release ! (I just noticed it)
https://github.com/horiuchi/dtsgenerator#v331-2020-10-05

**Comment by horiuchi** [comment]
It is old and will be closed once.
If you still have problems, please reopen it.
