### ISSUE TITLE
input type 'file'

### ISSUE THREAD

**Issue by Christian24** [horiuchi/dtsgenerator#496]
Hello,

I ran into an issue today with dtsgenerator not knowing how to work with the `file` type. This is apparently only available in OpenAPI version 2.0: https://swagger.io/docs/specification/data-models/data-types/#file Are there plans to support it? My life does not depend on it, just stumbled upon it by accident. 

On a similar note wouldn't it be a good idea to not throw an error when a type is unknown here: https://github.com/horiuchi/dtsgenerator/blob/e072d5c9ddd848ea317ae0cfb971513fc57d1288/src/core/utils.ts#L34
Wouldn't it be enough to just return something like `any` or `unknown` and just display a warning to the console?

Would love to hear your opinion on the matter @horiuchi :)

Thanks,
Christian

**Comment by horiuchi** [comment]
Indeed, it seems that only OpenAPI v2 has `type: file`.
Since this type does not exist in the original JSON Schema specification, it was not supported by the `dtsgenerator`.

But do you need support for `file`?
Even in the link, you provided, it looks like it says to use `type: string` instead of `type: file`.
The data structure used in the request/response also seems to be a `string` or some kind of `object`, since it will receive the file path and the contents of the file.
In OpenAPI v3 specification, there is no `type: file`, and there are examples of using `string`.
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#considerations-for-file-uploads

So I don't think there is much need to add `type: file` support now.

**Comment by horiuchi** [comment]
You are right.
It's a problem when it comes to errors in the current behavior.
Thanks for the good point.

I'll change this behavior.

**Comment by horiuchi** [comment]
Released by v3.12.0
